# Generated by Django 5.1.1 on 2024-09-05 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_fabrication',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
