# Generated by Django 5.1.1 on 2024-10-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ttc',
        ),
        migrations.CreateModel(
            name='Fournit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_ht', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire HT')),
                ('price_ttc', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire TTC')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LesProduits.fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LesProduits.product')),
            ],
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='products',
            field=models.ManyToManyField(related_name='fournisseurs', through='LesProduits.Fournit', to='LesProduits.product'),
        ),
    ]
