# Generated by Django 5.1.1 on 2024-10-10 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0002_fournisseur_remove_product_price_ht_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'En préparation'), (1, 'Passée'), (2, 'Reçue')], default=0)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LesProduits.fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LesProduits.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
