# Generated by Django 5.1.1 on 2024-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0003_product_stock_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='fournit',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
