# Generated by Django 5.1.2 on 2024-10-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0004_remove_product_stock_fournit_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantity',
        ),
        migrations.CreateModel(
            name='CommandeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LesProduits.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LesProduits.product')),
            ],
        ),
    ]
