# Generated by Django 5.1.2 on 2024-10-16 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0005_remove_commande_fournisseur_remove_commande_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='product',
        ),
    ]
