# Generated by Django 5.1.1 on 2024-10-16 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LesProduits', '0006_remove_commande_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LesProduits.fournisseur'),
        ),
    ]
